apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8sgpt-azure-extensions.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8sgpt-azure-extensions.labels" . | nindent 4 }}
data:
  k8sgpt.yaml: |
    active_filters:
      {{- range (splitList "," .Values.analyze.filters) }}
      - {{ . | trim }}
      {{- end }}
    ai:
      providers:
        - name: {{ .Values.ai.backend }}
          model: {{ .Values.ai.model }}
          {{- if .Values.ai.baseUrl }}
          baseurl: {{ .Values.ai.baseUrl }}
          {{- end }}
          {{- if .Values.ai.engine }}
          engine: {{ .Values.ai.engine }}
          {{- end }}
          temperature: {{ .Values.ai.temperature }}
      defaultprovider: {{ .Values.ai.backend }}
    integrations:
      azureextensions:
        enabled: true
