{{- if and .Values.ai_secret.aiPassword (not .Values.ai_secret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8sgpt-azure-extensions.fullname" . }}-ai-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8sgpt-azure-extensions.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.ai_secret.aiPassword | b64enc | quote }}
{{- end }}
